---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: cka-lab-ttyd
  name: cka-lab-ttyd
  namespace: cka
spec:
  replicas: 1
  selector:
    matchLabels:
      run: cka-lab-ttyd
  template:
    metadata:
      labels:
        run: cka-lab-ttyd
    spec:
      containers:
      - image: ssmiller25/cka_ng_lab_ttyd
        imagePullPolicy: Always
        name: cka-lab-ttyd
        ports:
          - containerPort: 7681
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: cka-lab-ttyd
  name: cka-lab-ttyd
spec:
  ports:
  - port: 7681
    protocol: TCP
    targetPort: 7681
  selector:
    run: cka-lab-ttyd
  sessionAffinity: None
  type: ClusterIP
